# -*- coding: utf-8 -*-
"""FathimaAkeela

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aHPOL43_2SCgPHcM_VMqtU0vIjdVXen4
"""

import requests

from datetime import datetime

api_key='d355241e3c5ac3c28b741bda1834c62e'
location=input("Enter the city name: ")

complete_api_link="https://api.openweathermap.org/data/2.5/weather?q="+location+"&appid="+api_key
api_link=requests.get(complete_api_link)
api_data=api_link.json()

temp_city = ((api_data['main']['temp']) - 273.15)
weather_desc = api_data['weather'][0]['description']
hmdt = api_data['main']['humidity']
wind_spd = api_data['wind']['speed']
date_time =datetime.now().strftime("%d %b %Y | %I:%M:%S %p")

file = open('weather_statistics.txt','w')

file.write("----------------------------------------------------------")
file.write("Weather stats for - {} || {} ".format(location.upper(),date_time))
file.write("----------------------------------------------------------")


file.write("Current temperature is : {:.2f} deg C".format(temp_city))
file.write("Current weather desc   : {}".format(weather_desc))
file.write("Current Humidity       : {} %".format(hmdt))
file.write("Current wind speed     : {} kmph".format(wind_spd))

file.close()